values: [
    { name: "Acceptance", description: "to be open to and accepting of myself, others, life etc" },
    { name: "Adventure", description: "to be adventurous; to actively seek, create, or explore novel or stimulating experiences" },
    { name: "Assertiveness", description: "to respectfully stand up for my rights and request what I want" },
    { name: "Authenticity", description: "to be authentic, genuine, real; to be true to myself" },
    { name: "Beauty", description: "to appreciate, create, nurture or cultivate beauty in myself, others, the environment etc" },
    { name: "Caring", description: "to be caring towards myself, others, the environment etc" },
    { name: "Challenge", description: "to keep challenging myself to grow, learn, improve" },
    { name: "Compassion", description: "to act with kindness towards those who are suffering" },
    { name: "Connection", description: "to engage fully in whatever I am doing, and be fully present with others" },
    { name: "Contribution", description: "to contribute, help, assist, or make a positive difference to myself or others" },
    { name: "Conformity", description: "to be respectful and obedient of rules and obligations" },
    { name: "Cooperation", description: "to be cooperative and collaborative with others" },
    { name: "Courage", description: "to be courageous or brave; to persist in the face of fear, threat, or difficulty" },
    { name: "Creativity", description: "to be creative or innovative" },
    { name: "Curiosity", description: "to be curious, open-minded and interested; to explore and discover" },
    { name: "Encouragement", description: "to encourage and reward behaviour that I value in myself or others" },
    { name: "Equality", description: "to treat others as equal to myself, and vice-versa" },
    { name: "Excitement", description: "to seek, create and engage in activities that are exciting, stimulating or thrilling" },
    { name: "Fairness", description: "to be fair to myself or others" },
    { name: "Fitness", description: "to maintain or improve my fitness; to look after my physical and mental health and wellbeing" },
    { name: "Flexibility", description: "to adjust and adapt readily to changing circumstances" },
    { name: "Freedom", description: "to live freely; to choose how I live and behave, or help others do likewise" },
    { name: "Friendliness", description: "to be friendly, companionable, or agreeable towards others" },
    { name: "Forgiveness", description: "to be forgiving towards myself or others" },
    { name: "Fun", description: "to be fun-loving; to seek, create, and engage in fun-filled activities" },
    { name: "Generosity", description: "to be generous, sharing and giving, to myself or others" },
    { name: "Gratitude", description: "to be grateful for and appreciative of the positive aspects of myself, others and life" },
    { name: "Honesty", description: "to be honest, truthful, and sincere with myself and others" },
    { name: "Humour", description: "to see and appreciate the humorous side of life" },
    { name: "Humility", description: "to be humble or modest; to let my achievements speak for themselves" },
    { name: "Industry", description: "to be industrious, hard-working, dedicated" },
    { name: "Independence", description: "to be self-supportive, and choose my own way of doing things" },
    { name: "Intimacy", description: "to open up, reveal, and share myself -- emotionally or physically – in my close personal relationships" },
    { name: "Justice", description: "to uphold justice and fairness" },
    { name: "Kindness", description: "to be kind, compassionate, considerate, nurturing or caring towards myself or others" },
    { name: "Love", description: "to act lovingly or affectionately towards myself or others" },
    { name: "Mindfulness", description: "to be conscious of, open to, and curious about my here-and-now experience" },
    { name: "Order", description: "to be orderly and organized" },
    { name: "Open-mindedness", description: "to think things through, see things from other’s points of view, and weigh evidence fairly" },
    { name: "Patience", description: "to wait calmly for what I want" },
    { name: "Persistence", description: "to continue resolutely, despite problems or difficulties" },
    { name: "Pleasure", description: "to create and give pleasure to myself or others" },
    { name: "Power", description: "to strongly influence or wield authority over others, leading, organizing" },
    { name: "Reciprocity", description: "to build relationships in which there is a fair balance of giving and taking" },
    { name: "Respect", description: "to be respectful towards myself or others; to be polite, considerate and show positive regard" },
    { name: "Responsibility", description: "to be responsible and accountable for my actions" },
    { name: "Romance", description: "to be romantic; to display and express love or strong affection" },
    { name: "Safety", description: "to secure, protect, or ensure safety of myself or others" },
    { name: "Self-awareness", description: "to be aware of my own thoughts, feelings and actions" },
    { name: "Self-care", description: "to look after my health and wellbeing, and get my needs met" },
    { name: "Self-development", description: "to keep growing, advancing or improving in knowledge, skills, character, or life experience" },
    { name: "Self-control", description: "to act in accordance with my own ideals" },
    { name: "Sensuality", description: "to create, explore and enjoy experiences that stimulate the five senses" },
    { name: "Sexuality", description: "to explore or express my sexuality" },
    { name: "Spirituality", description: "to connect with things bigger than myself" },
    { name: "Skilfulness", description: "to continually practice and improve my skills, and apply myself fully when using them" },
    { name: "Supportiveness", description: "to be supportive, helpful, encouraging, and available to myself or others" },
    { name: "Trust", description: "to be trustworthy; to be loyal, faithful, sincere, and reliable" },
]